# Configuration Compliance Check
#
# AUTHOR(s): Héctor Cavalcanti Saavedra <hcavalca@cisco.com>
# CONTRIBUTOR(s): Sarah Louise Justin <sajustin@cisco.com>

version: '3'
services: 
    web:
        build: ccc
        ports:
            - '5000:5000'
        env_file: 
            - .dev.env
        labels:
            com.cisco.author: "Héctor Cavalcanti Saavedra <hcavalca@cisco.com>"